"""Build a double-clickable macOS app that opens the dashboard and quits when you close the tab.

    python3 make_app.py                 # builds ~/Desktop/Environment Cost of Claude.app
    python3 make_app.py --dest ~/Applications
    make app

The app is a three-file bundle around one shell line: cd to this repo, set DASHBOARD_AUTOQUIT=1,
run dashboard.py. The auto-quit lives in dashboard.py, not here -- the page heartbeats while it is
open and the server exits once nobody is watching, so closing the tab leaves nothing running.

It is an LSUIElement agent, so it has no Dock icon and no menu bar: the browser tab is the whole
interface. That also means a crash would be silent, so stdout goes to
~/Library/Logs/environment-cost-of-claude.log and a missing repo raises a Finder dialog rather
than failing invisibly.

The icon is generated from the same mark as the favicon (make_favicon.svg), rasterised with
qlmanage and packed with iconutil. Building it also needs numpy and Pillow, which come with the
matplotlib the figures already require; nothing else in the dashboard depends on them.

The bundle embeds the absolute path of this repo, so it is built rather than committed: move the
repo and you rebuild the app.
"""
import argparse
import os
import pathlib
import plistlib
import shlex
import shutil
import subprocess
import sys
import tempfile

import make_favicon

NAME = "Environment Cost of Claude"
BUNDLE_ID = "eco.claudeenv.dashboard"
ICON_PAD = 3.2      # 32-unit canvas -> artwork on 80% of the grid, which is the macOS convention

LAUNCHER = """#!/bin/sh
# Generated by make_app.py -- do not edit, rebuild with `make app`.
REPO={repo}
PY={py}
LOG="$HOME/Library/Logs/environment-cost-of-claude.log"

[ -x "$PY" ] || PY=/usr/bin/python3
if [ ! -d "$REPO" ]; then
  osascript -e 'display alert "Environment Cost of Claude" message "The project folder has moved.\
 Rebuild the app with: make app"' >/dev/null 2>&1
  exit 1
fi
cd "$REPO" || exit 1
export DASHBOARD_AUTOQUIT=1
exec "$PY" dashboard.py >>"$LOG" 2>&1
"""


def run(cmd, **kw):
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kw)


def _render(svg_text, px, tmp, tag):
    """Rasterise one SVG with qlmanage, which names its output after the input, extension and all."""
    src = tmp / f"{tag}.svg"
    src.write_text(svg_text)
    run(["qlmanage", "-t", "-s", str(px), "-o", str(tmp), str(src)])
    out = tmp / f"{tag}.svg.png"
    if not out.exists():
        raise SystemExit("qlmanage produced no PNG — cannot build the icon")
    from PIL import Image
    return Image.open(out).convert("RGB")


def build_master(tmp, px=1024):
    """Render the mark with a real alpha channel.

    qlmanage is the only SVG rasteriser macOS ships, and it flattens onto opaque white -- so the
    obvious one-shot render gives a white square with the tile floating inside it, which looks
    fine in a preview and wrong in the Dock, where every other icon has a transparent margin.

    So render twice, over white and over black, and solve for the alpha that was thrown away.
    Compositing gives W = C + (1-a)*255 and K = C for premultiplied colour C, hence a = 255-(W-K)
    and the straight colour is K/a. Exact, including on the antialiased edge of the rounded
    corners -- which is the part that would otherwise show a dark or light fringe."""
    import numpy as np
    from PIL import Image

    mark = make_favicon.svg(pad=ICON_PAD)
    # The backdrop goes immediately after the opening <svg ...> tag, i.e. beneath the artwork.
    bg = lambda c: mark.replace(">", f'><rect width="32" height="32" fill="{c}"/>', 1)
    w = np.asarray(_render(bg("#ffffff"), px, tmp, "on-white"), dtype=float)
    k = np.asarray(_render(bg("#000000"), px, tmp, "on-black"), dtype=float)
    if w.shape != k.shape:
        raise SystemExit("the two renders disagree in size — cannot recover alpha")

    a = np.clip(255.0 - (w - k).max(axis=2), 0.0, 255.0)
    rgb = np.clip(k * 255.0 / np.maximum(a, 1.0)[..., None], 0.0, 255.0)
    return Image.fromarray(np.dstack([rgb, a]).astype(np.uint8), "RGBA")


def build_icns(dest):
    """Rasterise the mark at every size the Dock and Finder ask for, and pack it into a .icns."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        master = build_master(tmp)
        iconset = tmp / "icon.iconset"
        iconset.mkdir()
        from PIL import Image
        for size in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                px = size * scale
                name = f"icon_{size}x{size}{'@2x' if scale == 2 else ''}.png"
                # BOX (area average), not LANCZOS: at 1024->16 the Lanczos kernel rings, which
                # pushes alpha above zero outside the tile and leaves a faint halo on the
                # smallest icons. Area averaging is exactly right for flat vector artwork.
                master.resize((px, px), Image.BOX).save(iconset / name)
        run(["iconutil", "-c", "icns", str(iconset), "-o", str(dest)])


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dest", default="~/Desktop", help="where to put the app (default ~/Desktop)")
    a = ap.parse_args()

    repo = pathlib.Path(__file__).resolve().parent
    app = pathlib.Path(os.path.expanduser(a.dest)).resolve() / f"{NAME}.app"
    if not app.parent.is_dir():
        raise SystemExit(f"no such directory: {app.parent}")

    if app.exists():
        shutil.rmtree(app)
    macos, res = app / "Contents" / "MacOS", app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    res.mkdir(parents=True)

    plistlib.dump({
        "CFBundleName": NAME,
        "CFBundleDisplayName": NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": "launch",
        "CFBundleIconFile": "icon",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "1.0",
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "10.13",
        "LSUIElement": True,      # no Dock icon: the browser tab is the interface
        "NSHighResolutionCapable": True,
    }, open(app / "Contents" / "Info.plist", "wb"))

    launcher = macos / "launch"
    # Quoted with shlex so a space in the repo path cannot split the command.
    launcher.write_text(LAUNCHER.format(repo=shlex.quote(str(repo)), py=shlex.quote(sys.executable)))
    launcher.chmod(0o755)

    build_icns(res / "icon.icns")

    # Finder caches bundle metadata by mtime; without this the new icon can take minutes to appear.
    subprocess.run(["touch", str(app)], check=False)
    print(f"built {app}")
    print(f"  repo:        {repo}")
    print(f"  interpreter: {sys.executable}")
    print(f"  log:         ~/Library/Logs/environment-cost-of-claude.log")
    print("Double-click it. Closing the browser tab quits the server.")


if __name__ == "__main__":
    main()
